### ISSUE TITLE
Generate suggestions and copy them to clipboard

### ISSUE THREAD

**Issue by Violet-Vibes** [JamesShelton140/aqp-finder#1]
Would it be possible to have it generate possible suggestions and preferably, copy them to the clipboard? This would allow you faster time a correct W-response to a AQP-message so it lines up correctly by having a already generated message in your clipboard.

The user will still require to actively add the message (by pasting it) and manually send it.

**Comment by JamesShelton140** [comment]
I didn't think it was possible to paste into chat. Is there a plugin that enables that already? If not I'll need to make sure it's allowed before I try and add that functionality.

**Comment by Violet-Vibes** [comment]
> I didn't think it was possible to paste into chat. Is there a plugin that enables that already? If not I'll need to make sure it's allowed before I try and add that functionality.

Seems like it's only possible when the development plugin is turned on but yes, the functionality is there.

**Comment by JamesShelton140** [comment]
I didn't like the limited random character generator idea so I made an overlay that dynamically updates as text is typed into chat when a "q p" is available.

This can be used to match the W after typing random characters yourself or even full words/ sentences.

I consider this closed by 986c60a493454753b41f18b64729fc91767ac7f0
