### ISSUE TITLE
Malicious q p crashing

### ISSUE THREAD

**Issue by Zachpoole96** [JamesShelton140/aqp-finder#5]
I didn't think much of it until someone said in a CC, wanna see me get banned? 
and typed a q p [impossible] and ended up freezing my client and computer has I kept getting notifications from RL about a q p.

**Comment by JamesShelton140** [comment]
I've had this issue mentioned before but I've been unable to replicate it (issue #2). I would appreciate if you could give as much information as possible about the bug.

Things like:
- What are your setting for this plugin?
- What are your RuneLite settings related to notifications?
- Did this happen in an actual clan chat or a friends chat (the old CC)?
- Has this happened before? If so is it regular?

**Comment by Zachpoole96** [comment]
![PXL_20220724_004827398](https://user-images.githubusercontent.com/69546098/180627820-92ca4cec-a349-43bb-956b-fbcfeeb8a354.jpg)
![PXL_20220724_004803675](https://user-images.githubusercontent.com/69546098/180627823-2ead0a07-0c99-4e38-bafe-5bc98676cc2f.jpg)

The qp plugin settings are spaces and the only thing turned on are use overlay and inline hints 

![16586246023813546931011972840328](https://user-images.githubusercontent.com/69546098/180627860-d350a8ae-9f62-46e0-85be-274a79256b3e.jpg)

It happens in joining a cc, not sure which is which honestly.

And as for how regular, it varies. Because it's obviously very malicious the way they do it.

**Comment by JamesShelton140** [comment]
Thanks to your help I found the issue!

It's "Game message notifications" causing the problem as the notification message is `A  q p opportunity!` which itself contains a "q p".

I will fix the issue by changing the notification message to `A qp opportunity!`.
